version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kong
      POSTGRES_DB: kong
  kong:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    volumes:
      - ./kong:/etc/kong
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
    command: ["./wait-for-postgres.sh", "db", "./start-kong.sh", "-vv", "--nginx-conf", "/etc/kong/custom-nginx.template"]
